# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-b22da2f5-e52a-432d-9d20-8abf38b02beb";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b22da2f5-e52a-432d-9d20-8abf38b02beb".device = "/dev/disk/by-uuid/b22da2f5-e52a-432d-9d20-8abf38b02beb";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/354D-2010";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-b0966ec1-8037-4b7f-b8ec-092bbf698747"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
